# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];
  zramSwap = {
    enable = true;
    memoryMax = 1024 * 1024 * 1024;
  };
  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "sr_mod"
    "kvm_amd"
    "kvm"
    "vfio-pci"
    "vfio_iommu_type1"
    "vfio"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "cryptd"
  ];
  boot.kernelModules = [ ];

  boot.extraModprobeConfig = ''
    softdep nouveau pre: vfio-pci
    softdep nvidia pre: vfio-pci
    softdep nvidia* pre: vfio-pci
    options kvm_amd nested=1
    options kvm ignore_msrs=1
    options vfio-pci ids=10de:2482,10de:228b,1912:0014
  '';

  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "microcode.amd_sha_check=off"
    "iommu=pt"
    "iommu=1"
    "rootfstype=ext4"
    "video=efifb:off"
    "loglevel=3"
    "udev.log_priority=3"
    "xhci_hcd.quirks=270336"
    "transparent_hugepage=never"
    "rd.driver.pre=vfio-pci"
    "pcie_acs_override=downstream,multifunction"
    "ipv6.disable=1"
  ];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1baac3c9-c26f-43bb-8b5d-674e53e6b57d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-92a6b480-c42d-41cf-8ca1-3282d423f9c0".device =
    "/dev/disk/by-uuid/92a6b480-c42d-41cf-8ca1-3282d423f9c0";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/573C-341A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/cf7488e9-4f32-4454-aee0-d4bc7383e551";
    fsType = "ext4";
  };

  fileSystems."/mnt/backup" = {
    device = "/dev/disk/by-uuid/0b593e11-ad24-4b81-9224-f863a44f5d98";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/63d5edb1-b3f1-4525-99ed-659304e4005e";
    fsType = "ext4";
  };

  fileSystems."/mnt/libvirt" = {
    device = "/dev/disk/by-uuid/0b434c3c-70a0-4ba6-bc30-1e3adc765c28";
    fsType = "ext4";
  };

  swapDevices = [ ];

  age.secrets.ainstsda1-Virgo-key = {
    owner = "root";
    mode = "400";
    rekeyFile = "${inputs.secrets}/Virgo/disks/ainstsda1.key.age";
  };

  age.secrets.ainstsdb1-Virgo-key = {
    owner = "root";
    mode = "400";
    rekeyFile = "${inputs.secrets}/Virgo/disks/ainstsdb1.key.age";
  };

  age.secrets.ainstsdc1-Virgo-key = {
    owner = "root";
    mode = "400";
    rekeyFile = "${inputs.secrets}/Virgo/disks/ainstsdc1.key.age";
  };

  age.secrets.ainstsdd1-Virgo-key = {
    owner = "root";
    mode = "400";
    rekeyFile = "${inputs.secrets}/Virgo/disks/ainstsdd1.key.age";
  };

  age.secrets.ainstsde1-Virgo-key = {
    owner = "root";
    mode = "400";
    rekeyFile = "${inputs.secrets}/Virgo/disks/ainstsde1.key.age";
  };

  age.secrets.nvme2n1p1-Virgo-key = {
    owner = "root";
    mode = "400";
    rekeyFile = "${inputs.secrets}/Virgo/disks/nvme2n1p1.key.age";
  };

  environment.etc.crypttab = {
    mode = "0600";
    text = ''
      # <volume-name> <encrypted-device> [key-file] [options]
      #ainstsdd1 UUID=0201b90d-c3e2-4e0b-81a1-b0bf73b21007 ${config.age.secrets.ainstsdd1-Virgo-key.path} luks,key-slot=1
      ainstsdb1 UUID=e5ea3b7f-edfe-4aab-999c-d49b54bab21b ${config.age.secrets.ainstsdb1-Virgo-key.path} luks,key-slot=1
      ainstsde1 UUID=6adad7da-3bb9-4ffa-895f-8ddc5e26e0e1 ${config.age.secrets.ainstsde1-Virgo-key.path} luks,key-slot=1
      ainstsda1 UUID=ed67f5cb-e5ea-4efa-a6ef-0c47f1b1fdac ${config.age.secrets.ainstsda1-Virgo-key.path} luks,key-slot=1
      ainstsdc1 UUID=8f97e143-80b8-43a9-904c-248b1173a90d ${config.age.secrets.ainstsdc1-Virgo-key.path} luks,key-slot=1
      #ainstnvme2n1p1 UUID=6842e454-1b16-4470-8960-6b50d60443e5 ${config.age.secrets.nvme2n1p1-Virgo-key.path} luks,key-slot=0
    '';
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
