# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  inputs,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];
  zramSwap = {
    enable = true;
    memoryMax = 1024 * 1024 * 1024;
  };

  boot = {
    initrd = {
      availableKernelModules = [
        "ahci"
        "xhci_pci"
        "virtio_pci"
        "virtio_scsi"
        "sr_mod"
        "virtio_blk"
      ];
      kernelModules = [
        "dm-snapshot"
        "cryptd"
      ];
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  virtualisation.vmVariant = {
    # the following configuration is added only when building VM with `build-vm`
    virtualisation = {
      memorySize = 2048; # use 2048MiB memory
      cores = 3; # use 3 cpu cores
      graphics = true; # Boot the vm in a window.
      diskSize = 15000; # Virtual machine disk size in MB.
      resolution = {
        x = 1920;
        y = 1080;
      };
      qemu.virtioKeyboard = true;
    };

  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
